formatter: "markdown table"

header-from: README.header.md
footer-from: README.footer.md

sections:
  hide:
    - header
    - footer
  show:
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: "README.md"
  mode: inject